name: Verium
author: EnderLuca
version: 0.0.1.0
main: me.enderluca.verium.VeriumPlugin
api-version: 1.21.3
load: STARTUP
depend:
  - ProtocolLib

commands:
  timer:
    description: Starting, stopping and pausing the timer
    usage: /timer (start / pause / set [<seconds>] [<minutes>] [<hours>] [<days>] / sync / enable / disable)
  reset:
    description: Resets the world and restarts the server
    usage: /reset (confirm)
  challenges:
    description: Shows a gui to manage the active challenges
    usage: /challenges
  modifiers:
    description: Show a gui to manage modifiers which make it harder or easier
    usage: /modifiers
  pause:
    description: Pauses all challenges
    usage: /pause
  resume:
    description: Resumes the challenge after it was paused or a challenge failed
    usage: /resume
  goals:
    description: Show gui to manage the active goals
    usage: /goals
  attributemanager:
    description: Shows a gui to manage the attributes of all players, for example the max health or the speed
    usage: /attributemanager
  time:
    description: Works in the same away as the vanilla time command, except that just /time opens a gui to set and freeze the time
    usage: /time (set <time> / add <time> / query (daytime / gametime / day))