name: Verium
author: EnderLuca
version: 0.0.2.2
main: me.enderluca.verium.VeriumPlugin
api-version: 1.20
load: STARTUP

commands:
  timer:
    description: Starting, stopping and pausing the timer
    usage: /timer (start / pause / set [<seconds>] [<minutes>] [<hours>] [<days>] / sync / enable / disable)
  reset:
    description: Resets the world and restarts the server
    usage: /reset (confirm)
  challenges:
    description: Shows a gui to manage the active challenges
    usage: /challenges
