name: Verium
author: EnderLuca
version: 0.0.5.0
main: me.enderluca.verium.VeriumPlugin
api-version: 1.20
load: STARTUP

commands:
  timer:
    description: Starting, stopping and pausing the timer
    usage: /timer (start / pause / set [<seconds>] [<minutes>] [<hours>] [<days>] / sync / enable / disable)
  reset:
    description: Resets the world and restarts the server
    usage: /reset (confirm)
  challenges:
    description: Shows a gui to manage the active challenges
    usage: /challenges
  gamerules:
    description: Show a gui to manage active game rules like NoHunger, PvP, etc...
    usage: /gamerules
  pause:
    description: Pauses all challenges
    usage: /pause
  resume:
    description: Resumes the challenge after it was paused or a challenge failed
    usage: /resume
  goals:
    description: Show gui to manage the active goals
    usage: /goals
  setmaxhealth:
    description: Sets the max health of all players to the specified value
    usage: /setmaxhealth [<hp>]